Bump `axi` to patched v0.32.1-dev

diff --git a/hardware/deps/axi/.github/workflows/doc.yml b/hardware/deps/axi/.github/workflows/doc.yml
--- a/hardware/deps/axi/.github/workflows/doc.yml
+++ b/hardware/deps/axi/.github/workflows/doc.yml
@@ -6,6 +6,10 @@ on:
       - v**       # such branch names conflict with tags
     tags:
       - v**
+  pull_request:
+    branches-ignore:
+      - gh-pages  # deployment target branch (this workflow should not exist on that branch anyway)
+      - v**       # such branch names conflict with tags
 
 jobs:
   build-and-deploy:
@@ -39,7 +43,7 @@ jobs:
         run: |
           rustup update stable --no-self-update && rustup default stable
           if ! $(which bender); then
-            cargo install bender --version 0.18.0
+            cargo install bender --version 0.23.1
           fi
           if ! $(which morty); then
             cargo install --git https://github.com/zarubaf/morty --rev 4855119c1378d45d9ac35cfa525725d2786e68f3
@@ -54,16 +58,26 @@ jobs:
 
       - name: Determine documentation target folder
         run: |
-          if echo $GITHUB_REF | grep -qE '^refs/(heads|tags)'; then
-            DOC_TARGET="$(echo $GITHUB_REF | cut -d '/' -f3-)"
+          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
+            DOC_TARGET="$GITHUB_HEAD_REF"
+          elif [ "$GITHUB_EVENT_NAME" == "push" ]; then
+            if echo $GITHUB_REF | grep -qE '^refs/(head|tag)s'; then
+              DOC_TARGET="$(echo $GITHUB_REF | cut -d '/' -f3-)"
+            else
+              echo "Error: Could not derive documentation target folder for ref '$GITHUB_REF'!"
+              exit 1
+            fi
           else
-            echo "Error: Could not derive documentation target folder for ref '$GITHUB_REF'!"
+            echo "Error: Unsupported event: '$GITHUB_EVENT_NAME'!"
             exit 1
           fi
-          echo "::set-env name=DOC_TARGET::$DOC_TARGET"
+          echo "DOC_TARGET=$DOC_TARGET" >> $GITHUB_ENV
 
       - name: Deploy documentation
         uses: JamesIves/github-pages-deploy-action@releases/v3
+        if: >
+          github.event_name == 'push'
+          || github.event.pull_request.head.repo.full_name == github.repository
         with:
           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
           BRANCH: gh-pages # The branch the action should deploy to.
